name: MagmaCoin
version: 1.0
author: Wolf_IV
main: com.Wolf_IV.MagmaCoin.MagMain
commands:
  startcount:
    description: Starts Counter
    permission: startcount.use
  endcount:
    description: Ends Counter
    permission: endcount.use